title: Jayaraj T
description: Staff MLOps Engineer | AI/ML | Cloud | Responsible AI
theme: jekyll-theme-minimal
logo: /assets/images/profile.jpg
github: https://github.com/jraj13
linkedin: https://linkedin.com/in/jayraj13
email: jraj.rel@outlook.com
